name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libgl1-mesa-dev xorg-dev

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install GL
      run: go get -u github.com/go-gl/gl/v3.2-core/gl
      env:
        CGO_ENABLED: 1

    - name: Test
      run: go test -v ./...
      env:
        CGO_ENABLED: 1
